In [1]:
import tensorflow as tf
import tensorflow_datasets as tfds
mnist_data = tfds.load("fashion_mnist")
for item in mnist_data:
    print(item)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/60000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/fashion_mnist/3.0.1.incomplete9UYQ82/fashion_mnist-train.tfrecord*...:   0…

Generating test examples...:   0%|          | 0/10000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/fashion_mnist/3.0.1.incomplete9UYQ82/fashion_mnist-test.tfrecord*...:   0%…

Dataset fashion_mnist downloaded and prepared to /root/tensorflow_datasets/fashion_mnist/3.0.1. Subsequent calls will reuse this data.
train
test


In [2]:
type(mnist_data)

dict

In [6]:
# This returns DatasetAdapter object
mnist_train, info = tfds.load("fashion_mnist", split = 'train', with_info=True)
assert isinstance(mnist_train, tf.data.Dataset)
print(type(mnist_train))
print(info)

<class 'tensorflow.python.data.ops.prefetch_op._PrefetchDataset'>
tfds.core.DatasetInfo(
    name='fashion_mnist',
    full_name='fashion_mnist/3.0.1',
    description="""
    Fashion-MNIST is a dataset of Zalando's article images consisting of a training set of 60,000 examples and a test set of 10,000 examples. Each example is a 28x28 grayscale image, associated with a label from 10 classes.
    """,
    homepage='https://github.com/zalandoresearch/fashion-mnist',
    data_path='/root/tensorflow_datasets/fashion_mnist/3.0.1',
    file_format=tfrecord,
    download_size=29.45 MiB,
    dataset_size=36.42 MiB,
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=uint8),
        'label': ClassLabel(shape=(), dtype=int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=60000, num_shards=1>,
    },
    citati

In [5]:
for item in mnist_train.take(1):
  print(type(item))
  print(item.keys())
  print(item['image'])
  print(item['label'])

<class 'dict'>
dict_keys(['image', 'label'])
tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 18]
  [ 77]
  [227]
  [227]
  [208]
  [210]
  [225]
  [216]
  [ 85]
  [ 32]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 61]
  [100]
  [ 97]
  [ 80]
  [ 57]
  [117]
  [227]
  [238]
  [115]
  [ 49]
  [ 78]
  [106]
  [108]
  [ 71]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 81]
  [105]
  [ 80]
  [ 69]
  [ 72]
  [ 64]
  [ 44]
  [ 21]
  [ 13]
  [ 44]
  [ 69]
  [ 75]
  [ 75]
  [ 80]
  [114]
  [ 80]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 26]
  [ 92]
  [ 69]
  [ 68]
  [ 75]
  [ 75]
  [ 71]
  [ 74]
  [ 83]
  [ 75]
  [ 77]
  [ 78]
  [ 74]
  [ 74]
  [ 83]
  [ 77]
  [108]
  [ 34]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]


In [7]:
# Using datasets from Keras
mnist = tf.keras.datasets.fashion_mnist
(training_images, training_labels), (testing_images, testing_labels) = mnist.load_data()

4422102/4422102 [==============================] - 1s 0us/step


In [11]:
# Fachion Mnist
 (training_images, training_labels), (testing_images, testing_labels) = tfds.as_numpy(tfds.load('fashion_mnist', split = ['train', 'test'], batch_size = -1, as_supervised = True))

training_images = training_images/255.0
testing_images = testing_images/255.0

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28, 28, 1)),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation = tf.nn.softmax)
])

model.compile(optimizer = 'adam', loss='sparse_categorical_crossentropy', metrics= ['accuracy'])

model.fit(training_images, training_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.5351 - accuracy: 0.8091
Epoch 2/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.4011 - accuracy: 0.8551
Epoch 3/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.3687 - accuracy: 0.8651
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.3473 - accuracy: 0.8729
Epoch 5/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.3310 - accuracy: 0.8785


In [14]:
# Horse or Human
data = tfds.load('horses_or_humans', split='train', as_supervised = True)
validation_data = tfds.load('horses_or_humans', split='test', as_supervised = True)
train_batches = data.shuffle(100).batch(10)
validation_batches = validation_data.batch(32)
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(16, (3, 3), activation ='relu',input_shape=(300, 300, 3)),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(32,(3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(64,(3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(64,(3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(64,(3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(1, activation = 'sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(train_batches, epochs = 10, validation_data=validation_batches, validation_steps = 1)

Epoch 1/10
103/103 [==============================] - 125s 1s/step - loss: 1.5105 - accuracy: 0.8598 - val_loss: 1.3467 - val_accuracy: 0.7812
Epoch 2/10
103/103 [==============================] - 117s 1s/step - loss: 0.1809 - accuracy: 0.9416 - val_loss: 0.7487 - val_accuracy: 0.8750
Epoch 3/10
103/103 [==============================] - 113s 1s/step - loss: 0.2011 - accuracy: 0.9250 - val_loss: 1.6163 - val_accuracy: 0.8438
Epoch 4/10
103/103 [==============================] - 115s 1s/step - loss: 0.0569 - accuracy: 0.9786 - val_loss: 1.2244 - val_accuracy: 0.8750
Epoch 5/10
103/103 [==============================] - 112s 1s/step - loss: 0.0046 - accuracy: 0.9981 - val_loss: 2.0036 - val_accuracy: 0.8750
Epoch 6/10
103/103 [==============================] - 113s 1s/step - loss: 3.1246e-04 - accuracy: 1.0000 - val_loss: 1.2092 - val_accuracy: 0.9375
Epoch 7/10
103/103 [==============================] - 116s 1s/step - loss: 5.7488e-05 - accuracy: 1.0000 - val_loss: 1.2631 - val_accuracy